services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_go
    restart: unless-stopped
    ports:
      - "${PORTFOLIO_PORT:-8080}:8080"
    environment:
      - PORT=8080
      - APP_ENV=${APP_ENV:-production}
      - DEFAULT_LANG=${DEFAULT_LANG:-pt}
      - DOMAIN=${DOMAIN:-diegocamargo.dev}
    networks:
      - homelab_network

networks:
  homelab_network:
    name: homelab_network
